name: Build

on:
  push:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Checkout project
        uses: actions/checkout@v2
      -
        name: Build
        run: |
         docker build -t entropy .
