name: Test

on:
  push:

jobs:
  test:
    runs-on: [ubuntu-latest]
    container:
      image: golang:1.16-buster
    steps:
      -
        name: Checkout project
        uses: actions/checkout@v2
      -
        name: Run test
        run: |
         go test -cover
